name: TechChallenge-Modulo-2-Fiap

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v2
        with: 
          dotnet-version: 8.0.x
          
      - name: Restore dependencies
        run: dotnet restore ./TechChallenge_Contatos_DDD.sln
        
      - name: Build
        run: dotnet build ./TechChallenge_Contatos_DDD.sln --no-restore
        
  unit_tests:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '8.0.x'

      - name: Run unit tests
        run: dotnet test ./TechChallenge-Modulo-2-Fiap/Tests --no-build --configuration Release --collect:"XPlat Code Coverage"
        
